{% set version = "0.3.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rang
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rang_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rang/rang_{{ version }}.tar.gz
  sha256: cbdbbc7b47293b350d69032b994e99d785a4f83d8b8bdffbda7e5e3493cbacbc

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-fastmap
    - r-here
    - r-httr
    - r-jsonlite
    - r-memoise
    - r-parsedate
    - r-pkgsearch
    - r-remotes
    - r-renv
    - r-vctrs

  run:
    - r-base
    - r-fastmap
    - r-here
    - r-httr
    - r-jsonlite
    - r-memoise
    - r-parsedate
    - r-pkgsearch
    - r-remotes
    - r-renv
    - r-vctrs

test:
  commands:
    - $R -e "library('rang')"           # [not win]
    - "\"%R%\" -e \"library('rang')\""  # [win]

about:
  home: https://github.com/chainsawriot/rang
  license: GPL-3.0-or-later
  summary: Resolve the dependency graph of R packages at a specific time point based on the information from various 'R-hub' web services <https://blog.r-hub.io/>. The dependency graph can then be used to reconstruct the R computational environment with 'Rocker' <https://rocker-project.org>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan
